# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- molecule_test

pool: Services-Pool
  
steps:

- script: python -m pip install "molecule[podman,lint]" "ansible" "podman" "ansible-lint" 
  displayName: Install dependencies
  
- script: molecule test
  displayName: 'Run molecule test'