# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: master
  paths: 
    exclude: '*.md'

pool: Services-Pool

steps:

- script: |
    source scl_source enable rh-python38
    python3 -m venv ../venv
    . ../venv/bin/activate
    pip install --upgrade pip
    python3 -m pip install "molecule[podman,lint]" "ansible" "podman" "ansible-lint"
  displayName: Install dependencies

- script: |
    source scl_source enable rh-python38
    . ../venv/bin/activate
    molecule test
  displayName: 'Run molecule test'

- task: mspremier.CreateWorkItem.CreateWorkItem-task.CreateWorkItem@1
  displayName: 'APPLICATION: Create bug item'
  condition: failed()
  inputs:
    teamProject: 'technology-infrastructure-services'
    workItemType: bug
    title: 'DCStatus: Error on $(System.StageName) [$(Agent.MachineName)]'
    assignedTo: Bruno Raphael do Valle Xavier <bruno.valle@stone.com.br>
    fieldMappings: |
      System Info = Um erro foi encontrado no Deploy da Aplicação! Deseja conferir os detalhes clique em https://stonepagamentos.visualstudio.com/technology-infrastructure-services/_build/results?buildId=$(Build.BuildId)&view=results
      Found In = $(Build.BuildId)
      Environment = ${{parameters.AZURE_DEVOPS_ENVIRONMENT_TAG}}