# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: master
  paths: 
    exclude: '*.md'

pool: Services-Pool

steps:

- script: |
    source scl_source enable rh-python 38
    python3 -m venv ../venv
    . ../venv/bin/activate
    pip install --upgrade pip
    python3 -m pip install "molecule[podman,lint]" "ansible" "podman" "ansible-lint"
  displayName: Install dependencies

- script: |
    source scl_source enable rh-python38
    . ../venv/bin/activate
    molecule test
  displayName: 'Run molecule test'

- task: mspremier.CreateWorkItem.CreateWorkItem-task.CreateWorkItem@1
  displayName: 'APPLICATION: Create bug item'
  condition: failed()
  inputs:
    teamProject: 'technology-infrastructure-services'
    area path: 'technology-infrastructure-services\tis-automation'
    workItemType: bug
    title: 'Ansible-epel: Error on $(System.StageName) [$(Agent.MachineName)]'
    fieldMappings: |
      System Info = An error was found in the application deployment! Want to see the details? Click here https://stonepagamentos.visualstudio.com/technology-infrastructure-services/_build/results?buildId=$(Build.BuildId)&view=results
      Found In = $(Build.BuildId)
    