---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      local_tmp: /tmp
      remote_tmp: /tmp
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
