---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  options:
    interpreter_python: /opt/rh/rh-python38/root/bin/python3.8
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
